# Generated by Django 3.1.6 on 2021-02-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='user_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='county',
            new_name='user_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='user_full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='user_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postcode',
            new_name='user_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address1',
            new_name='user_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address2',
            new_name='user_street_address2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='town_or_city',
            new_name='user_town_or_city',
        ),
    ]
