# Generated by Django 3.1.6 on 2021-02-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210223_0813'),
        ('profiles', '0003_userprofile_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.ForeignKey(default='Bronze', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
