# Generated by Django 3.1.6 on 2021-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='meal_plan',
            field=models.CharField(choices=[('3 Month Plan', '3 Month Plan'), ('6 Month Plan', '6 Month Plan'), ('12 Month Plan', '12 Month Plan')], default='3 Month Plan', max_length=20),
        ),
    ]
