# Generated by Django 3.1.6 on 2021-02-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_meal_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_level',
            new_name='name',
        ),
    ]
