# Generated by Django 3.1.6 on 2021-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210223_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='image',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='priority',
            field=models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], default='bronze', max_length=10),
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
